# Generated by Django 5.1.4 on 2025-02-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_phone_number_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='membership_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
